# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0003_auto_20170125_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='SALT', max_length=255),
        ),
    ]
