# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('datefrom', models.DateTimeField(max_length=20)),
                ('dateto', models.DateTimeField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertravel', to='travelPlans.Destination')),
                ('joined_traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveluser', to='travelPlans.User')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveller', to='travelPlans.User'),
        ),
    ]
