# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='emailAddress',
        ),
    ]
