# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0002_auto_20170125_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailAddress',
            new_name='email',
        ),
    ]
