# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0004_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
